version: "3.7"
services:
  app:
    image: registry.gitlab.com/willhallonline/stackdemo:latest # docker service create --name registry --publish published=5000,target=5000 registry:2
    ports:
      - 8023:8000
    links:
      - redis
    deploy:
      mode: replicated
      replicas: 2
  redis:
    image: redis:alpine