version: "3.7"

services:
  drupal:
    image: drupal
    ports:
      - "8081:80"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
  laravel:
    image: bitnami/laravel
    ports:
      - "8082:80"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2

networks:
  overlay: