version: "3.7"

services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2

  mariadb:
    image: mariadb
    networks:
       - overlay
    deploy:
      replicas: 2

networks:
  overlay: