version: '3'
services:
  app:
    image: registry.gitlab.com/willhallonline/stackdemo:latest
    ports:
      - 8000:8000
    links:
      - redis
    deploy:
      mode: replicated
      replicas: 2
  redis:
    image: redis:alpine
