version: '3'
services:
  app:
    image: gitlab.com/willhallonline/stackdemo:latest # docker service create --name registry --publish published=5000,target=5000 registry:2
    build: .
    ports:
      - 8000:8000
    links:
      - redis
    deploy:
      mode: replicated
      replicas: 2
  redis:
    image: redis:alpine

# docker-compose push
# docker stack deploy --compose-file docker-compose.yml stackdemo
